google.maps.__gjsload__('onion', function(_){var EO,FO,PXa,IO,HO,SXa,TXa,UXa,RXa,VXa,JO,WXa,XXa,YXa,ZXa,$Xa,aYa,cYa,dYa,gYa,iYa,kYa,mYa,oYa,pYa,nYa,MO,NO,LO,OO,uYa,vYa,wYa,xYa,zYa,yYa,PO,HYa,GYa,SO,MYa,NYa,OYa,LYa,PYa,XYa,VO,ZYa,$Ya,QYa,RYa,SYa,WYa,cZa,dZa,aZa,bZa,TO,eZa,fZa,UO,TYa;EO=function(a,b,c=!1){return(b=(b?.jE()?b.Yv():void 0)?.wh())&&b.includes("/tiles?")?[b.replace("/tiles?","/featureMaps?")]:_.xx(a,c)};FO=function(a){return a.length>0&&a[0].includes("/featureMaps?")};
PXa=function(a,b){var c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};_.QXa=function(a,b){return _.gh(a,1,b)};IO=function(a){_.eH.call(this,a,GO);HO(a)};
HO=function(a){_.wG(a,GO)||(_.vG(a,GO,{entity:0,kp:1},["div",,1,0,[" ",["div",,1,1,[" ",["div",576,1,2,"Dutch Cheese Cakes"]," "]]," ",["div",,1,3,[" ",["span",576,1,4,"Central Station"]," ",["div",,1,5]," "]]," "]],[],RXa()),_.wG(a,"t-ZGhYQtxECIs")||_.vG(a,"t-ZGhYQtxECIs",{},["jsl",,1,0,[" A esta\u00e7\u00e3o \u00e9 acess\u00edvel "]],[],[["$t","t-ZGhYQtxECIs"]]))};SXa=function(a){return a.Rk};TXa=function(a){return a.xn};UXa=function(){return _.VF("t-ZGhYQtxECIs",{})};
RXa=function(){return[["$t","t-t0weeym2tCw","$a",[7,,,,,"transit-container"]],["display",function(a){return!_.YF(a.entity,b=>b.cw())}],["var",function(a){return a.Rk=_.WF(a.entity,"",b=>b.getTitle())},"$dc",[SXa,!1],"$a",[7,,,,,"gm-title"],"$a",[7,,,,,"gm-full-width"],"$c",[,,SXa]],["display",function(a){return _.YF(a.entity,b=>b.cw())},"$a",[7,,,,,"transit-title",,1]],["var",function(a){return a.xn=_.WF(a.entity,"",b=>b.ND(),b=>b.getName())},"$dc",[TXa,!1],"$c",[,,TXa]],["display",function(a){return _.WF(a.entity,
0,b=>b.ND(),b=>b.bT())==2},"$a",[7,,,,,"transit-wheelchair-icon",,1],"$uae",["aria-label",UXa],"$uae",["title",UXa],"$a",[0,,,,"img","role",,1]]]};VXa=function(a){return _.WF(a.icon,"",b=>b.jN())};JO=function(a){return a.Rk};WXa=function(a){return a.wk?_.UF("background-color",_.WF(a.component,"",b=>b.bp(),b=>b.Xl())):_.WF(a.component,"",b=>b.bp(),b=>b.Xl())};XXa=function(a){return _.WF(a.component,!1,b=>b.bp(),b=>b.OS())};YXa=function(a){return a.xn};
ZXa=function(){return[["$t","t-DjbQQShy8a0","$a",[7,,,,,"transit-container"]],["$a",[5,,,,function(a){return a.wk?_.UF("display",_.WF(a.kp,!1,b=>b.CD())?"none":""):_.WF(a.kp,!1,b=>b.CD())?"none":""},"display",,,1],"$up",["t-t0weeym2tCw",{entity:function(a){return a.entity},kp:function(a){return a.kp}}]],["for",[function(a,b){return a.Yp=b},function(a,b){return a.AN=b},function(a,b){return a.rT=b},function(a){return _.WF(a.entity,[],b=>b.ND(),b=>b.SS())}],"display",function(a){return _.YF(a.entity,
b=>b.cw())},"$a",[7,,,,,"transit-line-group"],"$a",[7,,,function(a){return a.AN!=0},,"transit-line-group-separator"]],["for",[function(a,b){return a.icon=b},function(a,b){return a.gT=b},function(a,b){return a.hT=b},function(a){return _.WF(a.Yp,[],b=>b.ZS())}],"$a",[0,,,,VXa,"alt",,,1],"$a",[8,2,,,function(a){return _.WF(a.icon,"",b=>b.qI(),b=>b[0],b=>b.getUrl())},"src",,,1],"$a",[0,,,,VXa,"title",,,1],"$a",[0,,,,"15","height",,1],"$a",[0,,,,"15","width",,1]],["var",function(a){return a.AE=_.WF(a.Yp,
0,b=>b.gI())==0?15:_.WF(a.Yp,0,b=>b.gI())==1?12:6},"var",function(a){return a.iQ=_.XF(a.Yp,b=>b.fI())>a.AE},"$a",[7,,,,,"transit-line-group-content",,1]],["for",[function(a,b){return a.line=b},function(a,b){return a.i=b},function(a,b){return a.qT=b},function(a){return _.WF(a.Yp,[],b=>b.fI())}],"display",function(a){return a.i<a.AE},"$up",["t-WxTvepIiu_w",{Yp:function(a){return a.Yp},line:function(a){return a.line}}]],["display",function(a){return a.iQ},"var",function(a){return a.RO=_.XF(a.Yp,b=>b.fI())-
a.AE},"$a",[7,,,,,"transit-nlines-more-msg",,1]],["var",function(a){return a.Rk=String(a.RO)},"$dc",[JO,!1],"$c",[,,JO]],["$a",[7,,,,,"transit-line-group-vehicle-icons",,1]],["$a",[7,,,,,"transit-clear-lines",,1]]]};
$Xa=function(){return[["$t","t-WxTvepIiu_w","display",function(a){return _.XF(a.line,b=>b.uN())>0},"var",function(a){return a.rE=_.YF(a.Yp,b=>b.dT())?_.WF(a.Yp,0,b=>b.gI()):2},"$a",[7,,,,,"transit-div-line-name"]],["$a",[7,,,function(a){return a.rE==2},,"gm-transit-long"],"$a",[7,,,function(a){return a.rE==1},,"gm-transit-medium"],"$a",[7,,,function(a){return a.rE==0},,"gm-transit-short"],"$a",[0,,,,"list","role"]],["for",[function(a,b){return a.component=b},function(a,b){return a.AS=b},function(a,
b){return a.BS=b},function(a){return _.WF(a.line,[],b=>b.uN())}],"$up",["t-LWeJzkXvAA0",{component:function(a){return a.component}}]]]};
aYa=function(){return[["$t","t-LWeJzkXvAA0","$a",[0,,,,"listitem","role"]],["display",function(a){return _.YF(a.component,b=>b.Jo())&&_.YF(a.component,b=>b.getIcon(),b=>b.qI(),b=>b[0],b=>b.Nm())},"$a",[7,,,,,"renderable-component-icon",,1],"$a",[0,,,,function(a){return _.WF(a.component,"",b=>b.getIcon(),b=>b.jN())},"alt",,,1],"$a",[8,2,,,function(a){return _.WF(a.component,"",b=>b.getIcon(),b=>b.qI(),b=>b[0],b=>b.getUrl())},"src",,,1],"$a",[0,,,,"15","height",,1],"$a",[0,,,,"15","width",,1]],["display",
function(a){return _.YF(a.component,b=>b.uI())},"var",function(a){return a.kT=_.WF(a.component,0,b=>b.getType())==5},"var",function(a){return a.mO=_.WF(a.component,"",b=>b.bp(),b=>b.Xl())=="#ffffff"},"var",function(a){return a.kE=_.YF(a.component,b=>b.bp(),b=>b.xy())}],["display",function(a){return!_.YF(a.component,b=>b.bp(),b=>b.yk())&&a.kE},"$a",[7,,,,,"renderable-component-color-box",,1],"$a",[5,5,,,WXa,"background-color",,,1]],["display",function(a){return _.YF(a.component,b=>b.bp(),b=>b.yk())&&
a.kE},"$a",[7,,,,,"renderable-component-text-box"],"$a",[7,,,XXa,,"renderable-component-bold"],"$a",[7,,,function(a){return a.mO},,"renderable-component-text-box-white"],"$a",[5,5,,,WXa,"background-color",,,1],"$a",[5,5,,,function(a){return a.wk?_.UF("color",_.WF(a.component,"",b=>b.bp(),b=>b.Ik())):_.WF(a.component,"",b=>b.bp(),b=>b.Ik())},"color",,,1]],["var",function(a){return a.Rk=_.WF(a.component,"",b=>b.bp(),b=>b.di())},"$dc",[JO,!1],"$a",[7,,,,,"renderable-component-text-box-content"],"$c",
[,,JO]],["display",function(a){return _.YF(a.component,b=>b.bp(),b=>b.yk())&&!a.kE},"var",function(a){return a.xn=_.WF(a.component,"",b=>b.bp(),b=>b.di())},"$dc",[YXa,!1],"$a",[7,,,,,"renderable-component-text"],"$a",[7,,,XXa,,"renderable-component-bold"],"$c",[,,YXa]]]};
cYa=function(a,b){a=_.yx({li:a.x,ni:a.y,wi:b});if(!a)return null;var c=2147483648/(1<<b);a=new _.Dn(a.li*c,a.ni*c);c=1073741824;b=Math.min(31,_.Gl(b,31));KO.length=Math.floor(b);for(let d=0;d<b;++d)KO[d]=bYa[(a.x&c?2:0)+(a.y&c?1:0)],c>>=1;return KO.join("")};dYa=function(a){return a.charAt(1)};gYa=function(a){var b=a.search(eYa);if(b!==-1){for(;a.charCodeAt(b)!==124;++b);return a.slice(0,b).replace(fYa,dYa)}return a.replace(fYa,dYa)};
_.hYa=function(a,b){var c=0;b.forEach((d,e)=>{(d.zIndex||0)<=(a.zIndex||0)&&(c=e+1)});b.insertAt(c,a)};iYa=function(a,b,c){b.data.remove(c);c.tiles.remove(b);c.tiles.getSize()||(a.data.remove(c),c.Kj=null,c.tiles=null)};kYa=function(a,b,c,d,e,f,g){var h="ofeatureMapTiles_"+b;_.Gm(c,"insert_at",()=>{a&&a[h]&&(a[h]={})});_.Gm(c,"remove_at",()=>{a&&a[h]&&(c.getLength()||(a[h]={}))});new jYa(c,d,e,f,(k,m)=>{a&&a[h]&&(a[h][`${k.coord.x}-${k.coord.y}-${k.zoom}`]=k.hasData);g&&g(k,m)})};
mYa=function(a,b,c){var d=a.qh[c.id]=a.qh[c.id]||{},e=b.toString();if(!d[e]&&!b.freeze){var f=new lYa([b].concat(b.rh||[]),[c]),g=b.secure;(b.rh||[]).forEach(m=>{g=g||m.secure});var h=g&&a.rh?a.rh:a.sh,k=h.load(f,m=>{delete d[e];var p=b.layerId;p=gYa(p);if(m=m&&m[c.DB]&&m[c.DB][p])m.Kj=b,m.tiles||(m.tiles=new _.Xp),_.gp(m.tiles,c),_.gp(b.data,m),_.gp(c.data,m);m={coord:c.uj,zoom:c.zoom,hasData:!!m};a.Qi&&a.Qi(m,b)});k&&(d[e]=()=>{h.cancel(k)})}};
oYa=function(a,b){var c=a.qh[b.id];for(let d in c)d&&nYa(a,b,d);delete a.qh[b.id]};pYa=function(a,b){a.tiles.forEach(c=>{c.id!=null&&mYa(a,b,c)})};nYa=function(a,b,c){if(a=a.qh[b.id])if(b=a[c])b(),delete a[c]};MO=function(a,b,c){this.rh=a;this.qh=b;this.wh=LO(this,1);this.sh=LO(this,3);this.th=c};NO=function(a,b){return a.rh.charCodeAt(b)-63};LO=function(a,b){return NO(a,b)<<6|NO(a,b+1)};OO=function(a,b){return NO(a,b)<<12|NO(a,b+1)<<6|NO(a,b+2)};
uYa=function(a,b,c=!1){return function(d,e){function f(h){var k={};for(let O=0,U=_.vl(h);O<U;++O){var m=h[O],p=m.layer;if(p==="")continue;p=gYa(p);var q=m.id;k[q]||(k[q]={});q=k[q];a:{if(!m){m=null;break a}let A=m.features;var u=m.base;delete m.base;let ha=(1<<m.id.length)/8388608;var x=m.id,z=0,B=0,L=1073741824;for(let ia=0,Ha=x.length;ia<Ha;++ia){let Ma=qYa[x.charAt(ia)];if(Ma==2||Ma==3)z+=L;if(Ma==1||Ma==3)B+=L;L>>=1}x=z;if(!A||!A.length){m=null;break a}z=m.epoch;z=typeof z==="number"&&m.layer?
{[m.layer]:z}:null;for(let ia of A)if(L=ia.a)L[0]+=u[0],L[1]+=u[1],L[0]-=x,L[1]-=B,L[0]*=ha,L[1]*=ha;u=[new rYa(A,z)];m.raster&&u.push(new MO(m.raster,A,z));m=new sYa(A,u)}q[p]=m?new tYa(m):null}e(k)}var g=a[(0,_.Cq)(d)%a.length];b||c?(d=c?(new _.xv(g+d)).toString():(0,_.Bq)((new _.xv(g)).setQuery(d,!0).toString()),_.cFa(d,{Qi:f,Do:f,KG:!0})):_.ny(_.Cq,g,_.Bq,d,f,f)}};
vYa=function(a,b,c,d,e){var f,g;a.qh&&a.ei.forEach(h=>{if(h.th&&b[h.Rp()]&&h.clickable!==!1){h=h.Rp();var k=b[h][0];k.bb&&(f=h,g=k)}});g||a.ei.forEach(h=>{b[h.Rp()]&&h.clickable!==!1&&(f=h.Rp(),g=b[f][0])});if(!f||!g||!g.id)return null;a=new _.Dn(0,0);e=1<<e;g.a?(a.x=(c.x+g.a[0])/e,a.y=(c.y+g.a[1])/e):(a.x=(c.x+d.x)/e,a.y=(c.y+d.y)/e);c=new _.Hn(0,0);d=g.bb;e=g.io;if(d&&d.length>=4&&d.length%4===0){e=e?_.$n(d[0],d[1],d[2],d[3]):null;let h=null;for(let k=d.length-4;k>=0;k-=4){let m=_.$n(d[k],d[k+1],
d[k+2],d[k+3]);m.equals(e)||(h?h.extendByBounds(m):h=m)}e?c.height=-e.getSize().height:h&&(c.width=h.minX+h.getSize().width/2,c.height=h.minY)}else e&&(c.width=e[0]||0,c.height=e[1]||0);return{feature:g,layerId:f,anchorPoint:a,anchorOffset:c}};wYa=function(a,b){var c={};a.forEach(d=>{var e=d.Kj;e.clickable!==!1&&(e=e.Rp(),d.get(b.x,b.y,c[e]=[]),c[e].length||delete c[e])});return c};xYa=function(a,b){return a.qh[b]&&a.qh[b][0]};
zYa=function(a,b){b.sort(function(d,e){return d.Rz.tiles[0].id<e.Rz.tiles[0].id?-1:1});for(var c=25/b[0].Rz.ei.length;b.length;){let d=b.splice(0,c),e=d.map(f=>f.Rz.tiles[0]);a.sh.load(new lYa(d[0].Rz.ei,e),yYa.bind(null,d))}};yYa=function(a,b){for(let c=0;c<a.length;++c)a[c].Qi(b)};
PO=function(a,b,c,d=!1){return _.oH(new _.AGa(new AYa(new BYa(uYa(a,c,d),()=>{var e={};b.get("tilt")&&!b.Mu&&(e.rJ="o",e.deg=String(b.get("heading")||0));var f=b.get("style");f&&(e.style=f);b.get("mapTypeId")==="roadmap"&&(e.JQ=!0);if(f=b.get("apistyle"))e.LG=f;f=b.get("authUser");f!=null&&(e.Bq=f);if(f=b.get("mapIdPaintOptions"))e.Tr=f;return e}))))};
HYa=function(a,b,c,d){function e(){var B=d?0:f.get("tilt"),L=d?0:a.get("heading"),O=a.get("authUser");return new CYa(g,k,b.getArray(),B,L,O,q)}var f=a.__gm,g=f.ai||(f.ai=new _.Xp),h=new DYa(d);d||(h.bindTo("tilt",f),h.bindTo("heading",a));h.bindTo("authUser",a);var k=_.wx(),m=EO(k,f.qh),p=EO(k,f.qh,!0);kYa(a,"onion",b,g,PO(m,h,!1,FO(m)),PO(p,h,!1,FO(p)));var q=void 0,u=e();h=u.qh();var x=_.Nn(h);_.zI(a,x,"overlayLayer",20,{dP(B){function L(){u=e();B.dQ(u)}b.addListener("insert_at",L);b.addListener("remove_at",
L);b.addListener("set_at",L)},eP(){_.Sm(u,"oniontilesloaded")}});var z=new EYa(b,!!_.op[15]);f.rh.then(B=>{var L=new FYa(b,g,z,f,x,B.Sh.topology);f.zh.register(L);GYa(L,c,a);var O=["mouseover","mouseout","mousemove"];for(let U of O)_.Gm(L,U,A=>{var ha=U,ia=xYa(c,A.layerId);if(ia){var Ha=a.get("projection").fromPointToLatLng(A.anchorPoint),Ma=null;A.feature.c&&(Ma=JSON.parse(A.feature.c));_.Sm(ia,ha,A.feature.id,Ha,A.anchorOffset,Ma,ia.layerId)}});_.Tu(B.Gv,U=>{U&&q!==U.Ci&&(q=U.Ci,u=e(),x.set(u.qh()))})})};
_.QO=function(a){var b=a.__gm;if(!b.Rh){let c=b.Rh=new _.fo,d=new IYa(c);b.sh.then(e=>{HYa(a,c,d,e)})}return b.Rh};_.JYa=function(a,b){b=_.QO(b);var c=-1;b.forEach((d,e)=>{d===a&&(c=e)});return c>=0?(b.removeAt(c),!0):!1};
GYa=function(a,b,c){var d=void 0;_.Gm(a,"click",e=>{d=window.setTimeout(()=>{var f=xYa(b,e.layerId);if(f){var g=c.get("projection").fromPointToLatLng(e.anchorPoint),h=f.sh;h?h(new _.KYa(f.layerId,e.feature.id,f.parameters),_.Sm.bind(_.Fr,f,"click",e.feature.id,g,e.anchorOffset)):(h=null,e.feature.c&&(h=JSON.parse(e.feature.c)),_.Sm(f,"click",e.feature.id,g,e.anchorOffset,null,h,f.layerId))}},300)});_.Gm(a,"dblclick",()=>{window.clearTimeout(d);d=void 0})};
SO=function(a){_.eH.call(this,a,RO);_.wG(a,RO)||(_.vG(a,RO,{entity:0,kp:1},["div",,1,0,[""," ",["div",,1,1,[" ",["div",,1,2,"Dutch Cheese Cakes"]," ",["div",,,6,[" ",["div",576,1,3,"29/43-45 E Canal Rd"]," "]]," "]],""," ",["div",,1,4,"transit info"]," ",["div",,,7,[" ",["a",,1,5,[" ",["span",,,,["Visualize no Google Maps"]]," "]]," "]]," "]],[],LYa()),HO(a),_.wG(a,"t-DjbQQShy8a0")||(_.vG(a,"t-DjbQQShy8a0",{entity:0,kp:1},["div",,1,0,[""," ",["div",,1,1,"transit info"]," ",["div",576,1,2,[" ",["div",
,,8,[" ",["img",8,1,3]," "]]," ",["div",,1,4,[" ",["div",,1,5,"Blue Mountains Line"]," ",["div",,,9]," ",["div",,1,6,["e ",["span",576,1,7,"5"]," outras."]]," "]]," "]]," "]],[],ZXa()),HO(a),_.wG(a,"t-WxTvepIiu_w")||(_.vG(a,"t-WxTvepIiu_w",{Yp:0,line:1},["div",,1,0,[" ",["div",576,1,1,[" ",["span",,1,2,"T1"]," "]]," "]],[],$Xa()),_.wG(a,"t-LWeJzkXvAA0")||_.vG(a,"t-LWeJzkXvAA0",{component:0},["span",,1,0,[["img",8,1,1],"",["span",,1,2,["",["div",,1,3],"",["span",576,1,4,[["span",576,1,5,"U1"]]],"",
["span",576,1,6,"Northern"]]],""]],[],aYa()))))};MYa=function(a){return a.entity};NYa=function(a){return a.kp};OYa=function(a){return a.Rk};
LYa=function(){return[["$t","t-Wtla7339NDI","$a",[7,,,,,"poi-info-window"],"$a",[7,,,,,"gm-style"]],["display",function(a){return!_.YF(a.entity,b=>b.cw())}],["$a",[5,,,,function(a){return a.wk?_.UF("display",_.WF(a.kp,!1,b=>b.CD())?"none":""):_.WF(a.kp,!1,b=>b.CD())?"none":""},"display",,,1],"$up",["t-t0weeym2tCw",{entity:MYa,kp:NYa}]],["for",[function(a,b){return a.PL=b},function(a,b){return a.pS=b},function(a,b){return a.qS=b},function(a){return _.WF(a.entity,[],b=>_.Ag(b,_.LI,3))}],"var",function(a){return a.Rk=
a.PL},"$dc",[OYa,!1],"$a",[7,,,,,"address-line"],"$a",[7,,,,,"full-width"],"$c",[,,OYa]],["display",function(a){return _.YF(a.entity,b=>b.cw())},"$up",["t-DjbQQShy8a0",{entity:MYa,kp:NYa}]],["$a",[8,1,,,function(a){return _.WF(a.kp,"",b=>b.aT())},"href",,,1],"$a",[0,,,,"_blank","target",,1]],["$a",[7,,,,,"address",,1]],["$a",[7,,,,,"view-link",,1]]]};PYa=function(a){return RegExp("^0x[a-fA-F0-9]{1,16}:0x[a-fA-F0-9]{1,16}$").test(a)};
XYa=function(a){var b;_.Gm(a.rh,"click",(c,d)=>{b=window.setTimeout(()=>{_.ME(161530);TO(a.map)||QYa(a);var e=RYa(a,c);if(e&&e.uu){var f=e.uu.id;if(f)if(TO(a.map))SYa(a,"smnoplaceclick",e.uu,e.Tj,f);else{_.ME(PYa(f)?381500:381501);if(PYa(f))if(f=_.RFa(f)){var g=new UO;var h=_.fe(f.rh);g=_.Rf(g,1,h==null?h:_.zE(h));f=_.fe(f.qh);f=_.Rf(g,2,f==null?f:_.zE(f));g=new TYa;f=_.Cg(g,UO,1,f);f=_.Kc(UYa(f),4)}else f=null;else f=null;if(f){if(g=f,h=a.map.get("projection"),a.wh=h&&h.fromPointToLatLng(e.Tj),a.wh&&
d.domEvent){var k=new VYa(a.wh,d.domEvent,g);_.Sm(a.map,"click",k)}}else k=void 0;k&&k.domEvent&&_.Ut(k.domEvent)||(a.anchorOffset=e.anchorOffset||_.Rn,WYa(a,f))}}},300)});_.Gm(a.rh,"dblclick",()=>{window.clearTimeout(b);b=void 0})};VO=function(a,b,c){a.rh&&_.Gm(a.rh,b,d=>{(d=RYa(a,d))&&d.uu&&TO(a.map)&&SYa(a,c,d.uu,d.Tj,d.uu.id||"")})};
ZYa=function(a){["ddsfeaturelayersclick","ddsfeaturelayersmousemove"].forEach(b=>{_.Gm(a.rh,b,(c,d,e)=>{var f=new Map;for(let h of e){e=(e=a.map.__gm.qh.Yv())?e.th():[];e=_.QFa(h,e,a.map);if(!e)continue;var g=a.map;let k=g.__gm,m=e.featureType==="DATASET"?e.datasetId:void 0;(g=_.Io(g,{featureType:e.featureType,datasetId:m}).isAvailable?e.featureType==="DATASET"?m?k.Ah.get(m)||null:null:k.th.get(e.featureType)||null:null)&&(f.has(g)?f.get(g)?.push(e):f.set(g,[e]))}if(f.size>0&&d.latLng&&d.domEvent)for(let [h,
k]of f)_.Sm(h,c,new YYa(d.latLng,d.domEvent,k))})})};$Ya=function(a){a.infoWindow&&a.infoWindow.set("map",null);a.qh=null};QYa=function(a){a.infoWindow||(_.nFa(a.map.getDiv()),a.infoWindow=new _.Wr({Vs:!0,logAsInternal:!0,headerDisabled:!0}),a.infoWindow.addListener("map_changed",()=>{a.infoWindow.get("map")||(a.qh=null)}))};RYa=function(a,b){var c=!_.op[35];return a.yh?a.yh(b,c):b};
SYa=function(a,b,c,d,e){d=a.map.get("projection").fromPointToLatLng(d);_.Sm(a.map,b,{featureId:e,latLng:d,queryString:c.query,aliasId:c.aliasId,tripIndex:c.tripIndex,adRef:c.adRef,featureIdFormat:c.featureIdFormat,incidentMetadata:c.incidentMetadata,hotelMetadata:c.hotelMetadata,loggedFeature:c.UI})};
WYa=async function(a,b){if(b&&a.infoWindow&&a.qh!==b){var c=a.wh,d=a.anchorOffset;a.qh=b;if(await aZa(a,b)){if(a.infoWindow){var e={disableAutoPan:!0};d&&(e.pixelOffset=d);a.infoWindow.setOptions(e);a.infoWindow.setPosition(c);a.infoWindow.setOptions({ariaLabel:"Detalhes do lugar"});a.infoWindow.get("map")||a.infoWindow.open({map:a.map})}a.sh.querySelector("gmp-place-details-place-request").place=b;await _.lBa(a.sh);a.qh===b&&a.infoWindow&&(a.infoWindow.setOptions({disableAutoPan:!1}),a.infoWindow.notify("position"),
a.infoWindow.focus())}}};cZa=async function(a){a.th||(a.th=await bZa());var b=a.th.gH,c=a.th.PlaceDetailsOrientation,d=_.el.rh();a=["gmp_2dm_pkit_v1_web",...(a.map.getInternalUsageAttributionIds()||[])];b=b({orientation:c.HORIZONTAL,internalUsageAttributionIds:a},{language:d.rh(),region:d.th(),showsAttribution:!1,showsTransit:!0});b.style.border="none";b.style.borderRadius="0";b.style.colorScheme="light";b.style.maxWidth="280px";b.style.minWidth="140px";return b};
dZa=function(a){a.xh||(a.xh=cZa(a).catch(b=>{a.xh=null;throw b;}));return a.xh};aZa=async function(a,b){if(a.sh)return!0;var c=await dZa(a);if(a.qh!==b||!a.infoWindow)return!1;a.sh=c;a.infoWindow.setContent(c);return!0};bZa=async function(){return _.cl("places")};TO=function(a){return _.op[18]&&(a.get("disableSIW")||a.get("disableSIWAndPDR"))};eZa=function(a){var b=""+a.getType(),c=_.Yf(a,_.uw,2);for(let d=0;d<c;++d)b+="|"+_.au(a,2,_.uw,d).getKey()+":"+_.au(a,2,_.uw,d).getValue();return encodeURIComponent(b)};
fZa=function(a,b){var c=a.anchorPoint,d=a.feature,e="",f=!1;if(d.c){var g=JSON.parse(d.c);e=g[31581606]&&g[31581606].entity&&g[31581606].entity.query||g[1]&&g[1].title||"";var h=document;e=e.indexOf("&")!=-1?_.cBa(e,h):e;var k=g[15]&&g[15].alias_id;var m=g[16]&&g[16].trip_index;h=g[29974456]&&g[29974456].ad_ref;var p=g[31581606]&&g[31581606].entity&&g[31581606].entity.feature_id_format;var q=g[31581606]&&g[31581606].entity;var u=g[43538507];var x=g[1]&&g[1].hotel_data;f=g[1]&&g[1].is_transit_station||
!1;var z=g[17]&&g[17].omnimaps_data;var B=g[28927125]&&g[28927125].directions_request;g=g[40154408]&&g[40154408].feature}return{Tj:c,uu:d.id&&d.id.indexOf("dti-")!==-1&&!b?null:{id:d.id,query:e,aliasId:k,anchor:d.a,adRef:h,entity:q,tripIndex:m,featureIdFormat:p,incidentMetadata:u,hotelMetadata:x,isTransitStation:f,HT:z,CM:B,UI:g},anchorOffset:a.anchorOffset||null}};_.ty.prototype.xy=_.fa(38,function(){return _.Tt(this,1)});UO=class extends _.J{constructor(a){super(a)}};
_.WO=class extends _.J{constructor(a){super(a)}getKey(){return _.I(this,1)}getValue(){return _.I(this,2)}setValue(a){return _.gh(this,2,a)}clearValue(){return _.Rf(this,2)}};_.gZa=[0,_.W,-1];TYa=class extends _.J{constructor(a){super(a,100)}Dl(){return _.yg(this,UO,1)}};_.qr[13258261]=_.tz;_.tb(IO,_.hH);IO.prototype.fill=function(a,b){_.fH(this,0,a);_.fH(this,1,b)};var GO="t-t0weeym2tCw";var bYa=["t","u","v","w"],KO=[];var fYa=/\*./g,eYa=/[^*](\*\*)*\|/;var lYa=class{constructor(a,b){this.ei=a;this.tiles=b}toString(){var a=this.tiles.map(b=>b.pov?`${b.id},${b.pov.toString()}`:b.id).join(";");return this.ei.join(";")+"|"+a}};var jYa=class{constructor(a,b,c,d,e){this.ei=a;this.tiles=b;this.sh=c;this.rh=d;this.qh={};this.Qi=e||null;_.Om(b,"insert",this,this.wh);_.Om(b,"remove",this,this.yh);_.Om(a,"insert_at",this,this.th);_.Om(a,"remove_at",this,this.xh);_.Om(a,"set_at",this,this.zh)}wh(a){a.DB=cYa(a.uj,a.zoom);a.DB!=null&&(a.id=a.DB+(a.gQ||""),this.ei.forEach(b=>{mYa(this,b,a)}))}yh(a){oYa(this,a);a.data.forEach(b=>{iYa(b.Kj,a,b)})}th(a){pYa(this,this.ei.getAt(a))}xh(a,b){this.zm(b)}zh(a,b){this.zm(b);pYa(this,this.ei.getAt(a))}zm(a){this.tiles.forEach(b=>
{nYa(this,b,a.toString())});a.data.forEach(b=>{b.tiles&&b.tiles.forEach(c=>{iYa(a,c,b)})})}};var DYa=class extends _.Um{constructor(a=!1){super();this.Mu=a}};_.KYa=class{constructor(a,b,c){this.layerId=a;this.featureId=b;this.parameters=c??{}}toString(){return`${this.layerId}|${this.featureId}`}};var tYa=class{constructor(a){this.qh=a;this.tiles=this.Kj=null}get(a,b,c){return this.qh.get(a,b,c)}jy(){return this.qh.jy()}Io(){return this.qh.Io()}};var rYa=class{constructor(a,b){this.qh=a;this.sh=new hZa;this.th=new iZa;this.rh=b}jy(){return this.qh}get(a,b,c){c=c||[];var d=this.qh,e=this.sh,f=this.th;f.x=a;f.y=b;for(let g=0,h=d.length;g<h;++g){a=d[g];b=a.a;let k=a.bb;if(b&&k)for(let m=0,p=k.length/4;m<p;++m){let q=m*4;e.minX=b[0]+k[q];e.minY=b[1]+k[q+1];e.maxX=b[0]+k[q+2]+1;e.maxY=b[1]+k[q+3]+1;if(e.containsPoint(f)){c.push(a);break}}}return c}Io(){return this.rh}},iZa=class{constructor(){this.y=this.x=0}},hZa=class{constructor(){this.minY=
this.minX=Infinity;this.maxY=this.maxX=-Infinity}containsPoint(a){return this.minX<=a.x&&a.x<this.maxX&&this.minY<=a.y&&a.y<this.maxY}};var sYa=class{constructor(a,b){this.rh=a;this.qh=b}jy(){return this.rh}get(a,b,c){c=c||[];for(let d=0,e=this.qh.length;d<e;d++)this.qh[d].get(a,b,c);return c}Io(){var a=null;for(let b of this.qh){let c=b.Io();if(a)c&&_.lba(a,c);else if(c){a={};for(let d in c)a[d]=c[d]}}return a}};_.aa=MO.prototype;_.aa.Tk=0;_.aa.iu=0;_.aa.Kq={};_.aa.jy=function(){return this.qh};_.aa.get=function(a,b,c){c=c||[];a=Math.round(a);b=Math.round(b);if(a<0||a>=this.wh||b<0||b>=this.sh)return c;var d=b==this.sh-1?this.rh.length:OO(this,5+(b+1)*3);this.Tk=OO(this,5+b*3);this.iu=0;for(this[8]();this.iu<=a&&this.Tk<d;)this[NO(this,this.Tk++)]();for(let e in this.Kq)c.push(this.qh[this.Kq[e]]);return c};_.aa.Io=function(){return this.th};MO.prototype[1]=function(){++this.iu};
MO.prototype[2]=function(){this.iu+=NO(this,this.Tk);++this.Tk};MO.prototype[3]=function(){this.iu+=LO(this,this.Tk);this.Tk+=2};MO.prototype[5]=function(){var a=NO(this,this.Tk);this.Kq[a]=a;++this.Tk};MO.prototype[6]=function(){var a=LO(this,this.Tk);this.Kq[a]=a;this.Tk+=2};MO.prototype[7]=function(){var a=OO(this,this.Tk);this.Kq[a]=a;this.Tk+=3};MO.prototype[8]=function(){for(let a in this.Kq)delete this.Kq[a]};MO.prototype[9]=function(){delete this.Kq[NO(this,this.Tk)];++this.Tk};
MO.prototype[10]=function(){delete this.Kq[LO(this,this.Tk)];this.Tk+=2};MO.prototype[11]=function(){delete this.Kq[OO(this,this.Tk)];this.Tk+=3};var qYa={t:0,u:1,v:2,w:3};var EYa=class{constructor(a,b){this.ei=a;this.qh=b}};var jZa=[new _.Dn(-5,0),new _.Dn(0,-5),new _.Dn(5,0),new _.Dn(0,5),new _.Dn(-5,-5),new _.Dn(-5,5),new _.Dn(5,-5),new _.Dn(5,5),new _.Dn(-10,0),new _.Dn(0,-10),new _.Dn(10,0),new _.Dn(0,10)],FYa=class{constructor(a,b,c,d,e,f){this.ei=a;this.wh=c;this.sh=d;this.zIndex=20;this.qh=this.rh=null;this.th=new _.iJ(b.elements,f,e)}jv(a){return a!=="dragstart"&&a!=="drag"&&a!=="dragend"}pv(a,b){return(b?jZa:[new _.Dn(0,0)]).some(function(c){c=_.yI(this.th,a.Tj,c);if(!c)return!1;var d=c.rp.wi,e=new _.Dn(c.Sv.li*
256,c.Sv.ni*256),f=new _.Dn(c.rp.li*256,c.rp.ni*256),g=wYa(c.Am.data,e),h=!1;this.ei.forEach(k=>{g[k.Rp()]&&(h=!0)});if(!h)return!1;c=vYa(this.wh,g,f,e,d);if(!c)return!1;this.rh=c;return!0},this)?this.rh.feature:null}handleEvent(a,b){if(a==="click"||a==="dblclick"||a==="rightclick"||a==="mouseover"||this.qh&&a==="mousemove"){var c=this.rh;if(a==="mouseover"||a==="mousemove")this.sh.set("cursor","pointer"),this.qh=c}else if(a==="mouseout")c=this.qh,this.sh.set("cursor",""),this.qh=null;else return;
a==="click"?_.Sm(this,a,c,b):_.Sm(this,a,c)}};var IYa=class{constructor(a){this.ei=a;this.qh={};_.Gm(a,"insert_at",this.insertAt.bind(this));_.Gm(a,"remove_at",this.removeAt.bind(this));_.Gm(a,"set_at",this.setAt.bind(this))}insertAt(a){a=this.ei.getAt(a);var b=a.Rp();this.qh[b]||(this.qh[b]=[]);this.qh[b].push(a)}removeAt(a,b){a=b.Rp();this.qh[a]&&_.Jl(this.qh[a],b)}setAt(a,b){this.removeAt(a,b);this.insertAt(a)}};var CYa=class extends _.at{constructor(a,b,c,d,e,f,g=_.QA){super();this.maxZoom=25;var h=PXa(c,m=>!(!m||!m.secure)),k=new _.NA;_.px(k,b.qh.rh(),b.qh.th());_.wc(c,m=>{m&&k.Rj(m)});this.rh=new kZa(a,new _.RA(_.xx(b,!!h),null,!1,_.yx,null,{Qo:k.request,Bq:f},d?e||0:void 0),g)}qh(){return this.rh}},kZa=class{constructor(a,b,c){this.tiles=a;this.wA=b;this.Ci=c;this.Gn=1}rm(a,b){var c=this.tiles,d={uj:new _.Dn(a.li,a.ni),zoom:a.wi,data:new _.Xp,gQ:_.jb(this)};a=this.wA.rm(a,{Ak:()=>{c.remove(d);b?.Ak?.()}});
d.div=a.qk();_.gp(c,d);return a}};var BYa=class{constructor(a,b){this.rh=a;this.qh=b}cancel(){}load(a,b){var c=new _.NA;_.px(c,_.el.rh().rh(),_.el.rh().th());_.Ana(c,3);for(var d of a.ei)if(d.mapTypeId&&d.qh){var e=d.mapTypeId,f=d.qh;var g=_.Nu();g=_.Jg(g,16);_.Cna(c,e,f,g)}for(var h of a.ei)h.mapTypeId&&_.yBa(h.mapTypeId)||c.Rj(h);e=this.qh();f=_.NE(e.deg);d=e.rJ==="o"?_.Bx(f):_.Bx();for(let k of a.tiles)(h=d({li:k.uj.x,ni:k.uj.y,wi:k.zoom}))&&_.Bna(c,h);if(e.JQ)for(let k of a.ei)k.roadmapStyler&&_.tx(c,k.roadmapStyler);for(let k of e.style||
[])_.tx(c,k);e.LG&&_.Xw(e.LG,_.gx(_.nx(c.request)));e.rJ==="o"&&(_.ah(c.request,13,f),_.Zg(c.request,14,!0));e.Tr&&_.Fna(c,e.Tr);a=`pb=${_.zna(_.rv(c.request,(0,_.MA)()))}`;e.Bq!=null&&(a+=`&authuser=${e.Bq}`);this.rh(a,b);return""}};var AYa=class{constructor(a){this.sh=a;this.qh=null;this.rh=0}load(a,b){this.qh||(this.qh={},_.QE(this.th.bind(this)));var c=a.tiles[0];c=`${c.zoom},${c.pov}|${a.ei.join(";")}`;this.qh[c]||(this.qh[c]=[]);this.qh[c].push({Rz:a,Qi:b});return`${++this.rh}`}cancel(){}th(){var a=this.qh;if(a){for(let b of Object.getOwnPropertyNames(a)){let c=a[b];c&&zYa(this,c)}this.qh=null}}};var YYa=class extends _.FA{constructor(a,b,c){super(a,b);this.features=c}};var VYa=class extends _.FA{constructor(a,b,c){super(a,b);this.placeId=c||null}};_.tb(SO,_.hH);SO.prototype.fill=function(a,b){_.fH(this,0,a);_.fH(this,1,b)};var RO="t-Wtla7339NDI";var UYa=_.EE(_.VGa);var lZa=class{constructor(a,b,c){this.map=a;this.rh=b;this.yh=c;this.qh=this.xh=this.sh=this.th=this.wh=this.anchorOffset=this.infoWindow=null;this.layout=new _.ZI(SO,{vt:_.gB.Jj()});new _.ZI(IO,{vt:_.gB.Jj()});XYa(this);VO(this,"rightclick","smnoplacerightclick");VO(this,"mouseover","smnoplacemouseover");VO(this,"mouseout","smnoplacemouseout");ZYa(this);_.Gm(this.map,"click",d=>{d&&d.placeId!==void 0||$Ya(this)})}};var mZa=class{constructor(a,b,c){function d(){x.Di()}this.map=a;this.rh=b;this.ei=c;this.qh=null;var e=new _.Xp,f=new _.Fra(e),g=a.__gm,h=new DYa;h.bindTo("authUser",g);h.bindTo("tilt",g);h.bindTo("heading",a);h.bindTo("style",g);h.bindTo("apistyle",g);h.bindTo("mapTypeId",a);_.koa(h,"mapIdPaintOptions",g.Tr);var k=_.wx();k=EO(k,g.qh);var m=!(new _.xv(k[0])).qh;h=PO(k,h,m,FO(k));var p=null,q=new _.TA(f,p||void 0),u=_.Nn(q),x=new _.dp(this.sh,0,this);d();_.Gm(a,"clickableicons_changed",d);_.Gm(g,"apistyle_changed",
d);_.Gm(g,"authuser_changed",d);_.Gm(g,"basemaptype_changed",d);_.Gm(g,"style_changed",d);g.Vl.addListener(d);b.Aj().addListener(d);kYa(this.map,"smartmaps",c,e,h,null,(B,L)=>{B=c.getAt(c.getLength()-1);if(L===B)for(;c.getLength()>1;)c.removeAt(0)});var z=new EYa(c,!1);a.__gm.rh.then(B=>{var L=new FYa(c,e,z,g,u,B.Sh.topology);L.zIndex=0;a.__gm.zh.register(L);this.qh=new lZa(a,L,fZa);_.Tu(B.Gv,O=>{O&&!O.Ci.equals(p)&&(p=O.Ci,q=new _.TA(f,p),u.set(q),d())})});_.zI(a,u,"mapPane",0)}sh(){var a=new _.Nx,
b=this.ei,c=this.map.__gm,d=c.get("baseMapType"),e=d&&d.Mw;if(e&&this.map.getClickableIcons()!==!1){var f=c.get("zoom");if(f=this.rh.HD(f?Math.round(f):f)){a.layerId=e.replace(/([mhr]@)\d+/,`$1${f}`);a.mapTypeId=d.mapTypeId;a.qh=f;var g=a.rh=a.rh||[];c.Vl.get().forEach(h=>{g.push(h)});d=c.get("apistyle")||"";f=c.get("style")||[];e=_.Cq;f=f.map(eZa).join(",");c=c.get("authUser");a.parameters.salt=e(`${d}+${f}${c}`);c=b.getAt(b.getLength()-1);if(!c||c.toString()!==a.toString()){c&&(c.freeze=!0);c=b.getLength();
for(d=0;d<c;++d)if(e=b.getAt(d),e.toString()===a.toString()){b.removeAt(d);e.freeze=!1;a=e;break}b.push(a)}}}else b.clear(),this.qh&&$Ya(this.qh),this.map.getClickableIcons()===!1&&_.M(this.map,148283)}};var nZa=class{YN(a,b){new mZa(a,b,a.__gm.Ph)}XL(a,b){new lZa(a,b,null)}};_.dl("onion",new nZa);});
